### ISSUE TITLE
Community.dns.wait_for_txt module fails on querying nameservers thart are IPv6 only

### ISSUE THREAD

**Issue by jimkoen** [ansible-collections/community.dns#120]
##### SUMMARY

When running the module as part of the [acme_certificate](https://github.com/felixfontein/ansible-acme/tree/main/roles/acme_certificate) role in the maintainers [ansible-acme](https://github.com/felixfontein/ansible-acme) collection,
the module does not resolve nameservers that have only an IPv6, but no IPv4 address.

Output logs show, that the module is unable to resolve nameservers that are only available via IPv6:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: ns1.os.h-da.cloud. IN A
fatal: [localhost]: FAILED! => {"changed": false, "completed": 0, "msg": "Unexpected DNS error: The DNS response does not contain an answer to the question: ns1.os.h-da.cloud. IN A", "records": [{"check_count": 0, "done": false, "name": "txt.test.pg.users.h-da.cloud"}]}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
wait_for_txt

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/Users/lucca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/lucca/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/lucca/.ansible/collections/ansible_collections
Collection    Version
------------- -------
community.dns 2.4.0  

# /usr/local/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible_collections
Collection    Version
------------- -------
community.dns 2.3.3  
```

##### CONFIGURATION

```paste below
# no changes
```

##### OS / ENVIRONMENT

Mac Mini 2018
Mac OS Monterey 12.5.1

##### STEPS TO REPRODUCE

The domain `txt.test.pg.users.h-da.cloud` has a TXT record of `"hello_ansible"`.
This is a real domain and I will leave this record up for testing. 

The authoritative nameservers for this domain are
 - control0.external.h-da.cloud.
 - ns1.os.h-da.cloud
 - ns2.os.h-da.cloud
 - ns3.os.h-da.cloud

You can test that record exists by running
```
# dig @control0.external.h-da.cloud. -t txt +short txt.test.pg.users.h-da.cloud
"hello_ansible"
# dig @ns1.os.h-da.cloud. -t txt +short txt.test.pg.users.h-da.cloud
"hello_ansible"
```
These will all resolve the record. The only difference between the ns1-3.os.h-da.cloud and the control0.external.h-da.cloud, that they are different names for the same DNS server, only that one is meant to be used on our internal network, and the other other for outside our network (public internet). They both work regardless from what network the queries are executed though, as these are just aliases (PTR-Records to the same server).

**Notice however that these resolve both via IPv6 exclusively.**
They do not have an A record, only an AAAA record, since they do not have an IPv4 address:
```
dig -t A +short ns1.os.h-da.cloud. 
# nothing

dig -t A +short control0.external.h-da.cloud.
# nothing

dig -t AAAA +short ns1.os.h-da.cloud.
2001:67c:295c:9004:f816::e16f

dig -t AAAA +short control0.external.h-da.cloud.
2001:67c:295c:9004:f816::e16f
```
The module does not seem to support IPv6 address lookup, as it is looking for an A record to resolve the NS:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: ns1.os.h-da.cloud. IN A
fatal: [localhost]: FAILED! => {"changed": false, "completed": 0, "msg": "Unexpected DNS error: The DNS response does not contain an answer to the question: ns1.os.h-da.cloud. IN A", "records": [{"check_count": 0, "done": false, "name": "txt.test.pg.users.h-da.cloud"}]}
```

You can reproduce the error by running the example playbook:

```yaml
- name: Test txt record lookup
  hosts: localhost
  tasks:
    - name: Wait for DNS entries to propagate
      community.dns.wait_for_txt:
        query_retry: 20
        records: 
          - name: txt.test.pg.users.h-da.cloud
            values: "hello_ansible"
            mode: equals
        timeout: 300
      run_once: true

```

##### EXPECTED RESULTS

The module detects that the NS is IPv6 only and examines the AAAA records as well.

##### ACTUAL RESULTS

The module fails in resolving the NS IPv6.

See the output from the `Wait for DNS entries to propagate` task below.
I ran the playbook with -vvvv

```paste below
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: lucca
<localhost> EXEC /bin/sh -c 'echo ~lucca && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/lucca/.ansible/tmp `"&& mkdir "` echo /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727 `" && echo ansible-tmp-1667873307.578681-76500-203754882649727="` echo /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727 `" ) && sleep 0'
Using module file /Users/lucca/.ansible/collections/ansible_collections/community/dns/plugins/modules/wait_for_txt.py
<localhost> PUT /Users/lucca/.ansible/tmp/ansible-local-7645537yviq0k/tmpza1_bolz TO /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727/AnsiballZ_wait_for_txt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727/ /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727/AnsiballZ_wait_for_txt.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/Cellar/ansible/6.5.0/libexec/bin/python3.10 /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727/AnsiballZ_wait_for_txt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/lucca/.ansible/tmp/ansible-tmp-1667873307.578681-76500-203754882649727/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/2x/3w11g_jn3ns0yp4tp4qgvw7h0000gn/T/ansible_community.dns.wait_for_txt_payload_rpamskat/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/modules/wait_for_txt.py", line 290, in main
  File "/var/folders/2x/3w11g_jn3ns0yp4tp4qgvw7h0000gn/T/ansible_community.dns.wait_for_txt_payload_rpamskat/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/modules/wait_for_txt.py", line 208, in lookup
  File "/var/folders/2x/3w11g_jn3ns0yp4tp4qgvw7h0000gn/T/ansible_community.dns.wait_for_txt_payload_rpamskat/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py", line 184, in resolve
    resolver = self._get_resolver(dnsname, [nameserver])
  File "/var/folders/2x/3w11g_jn3ns0yp4tp4qgvw7h0000gn/T/ansible_community.dns.wait_for_txt_payload_rpamskat/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py", line 149, in _get_resolver
    nameserver_ips.update(self._lookup_address(nameserver))
  File "/var/folders/2x/3w11g_jn3ns0yp4tp4qgvw7h0000gn/T/ansible_community.dns.wait_for_txt_payload_rpamskat/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py", line 101, in _lookup_address
    answer = self._handle_timeout(self.default_resolver.resolve, target, lifetime=self.timeout)
  File "/var/folders/2x/3w11g_jn3ns0yp4tp4qgvw7h0000gn/T/ansible_community.dns.wait_for_txt_payload_rpamskat/ansible_community.dns.wait_for_txt_payload.zip/ansible_collections/community/dns/plugins/module_utils/resolver.py", line 60, in _handle_timeout
    return function(*args, **kwargs)
  File "/Users/lucca/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dns/resolver.py", line 1202, in resolve
    (answer, done) = resolution.query_result(response, None)
  File "/Users/lucca/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dns/resolver.py", line 674, in query_result
    raise NoAnswer(response=answer.response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: ns1.os.h-da.cloud. IN A
fatal: [localhost]: FAILED! => {
    "changed": false,
    "completed": 0,
    "invocation": {
        "module_args": {
            "always_ask_default_resolver": true,
            "max_sleep": 10.0,
            "query_retry": 20,
            "query_timeout": 10.0,
            "records": [
                {
                    "mode": "equals",
                    "name": "txt.test.pg.users.h-da.cloud",
                    "values": [
                        "hello_ansible"
                    ]
                }
            ],
            "timeout": 300.0
        }
    },
    "msg": "Unexpected DNS error: The DNS response does not contain an answer to the question: ns1.os.h-da.cloud. IN A",
    "records": [
        {
            "check_count": 0,
            "done": false,
            "name": "txt.test.pg.users.h-da.cloud"
        }
    ]
}

```

**Comment by felixfontein** [comment]
I think #121 should fix this. I unfortunately don't have IPv6 at home, but when I ran the module on my server (which has IPv6) I was able to run your testcase successfully with my PR.

**Comment by jimkoen** [comment]
> I think #121 should fix this. I unfortunately don't have IPv6 at home, but when I ran the module on my server (which has IPv6) I was able to run your testcase successfully with my PR.

You're an absolute beast for fixing this this fast, thank you so much!
I will test the PR out tomorrow.
